import "./globals.css";



export const metadata = {
  title: "Demo App For Testing in Next Js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <p>Hello World For All My DEvice</p>
        {children}
      </body>
    </html>
  );
}
